export type User = {
  id: string;
  name: string;
  email: string;
  isAdmin: boolean;
  realName: string;
  firstName: string;
  profileSlug: string | null;
  publicProfileEnabled: boolean;
  bio: string;
  avatarId: string | null;
  defaultMarker: "mechanical" | "electric" | "rental";
};
export type Event = {
  id: string;
  ownerId: string;
  title: string;
  description: string;
  date: string;
  time: string;
  timezone: string;
  venue: string;
  address: string;
  capacity: number;
  currency: string;
  inviteToken: string;
  createdAt: string;
  theme: string;
  city: string;
  state: string;
  country: string;
  visibility: "private" | "public";
  accentColor: string;
  coverId: string | null;
  invitationCoverId: string | null;
  invitationHeading: string;
  invitationMessage: string;
  memberInvitesEnabled: boolean;
  sponsorsEnabled: boolean;
};
export type Guest = {
  firstName: string;
  profileSlug: string | null;
  loadoutPreview: string;
  attended: boolean;
  id: string;
  name: string;
  status: "going" | "maybe" | "declined";
  marker: "mechanical" | "electric" | "rental";
  team: string;
  notes: string;
  userId: string | null;
  avatarId: string | null;
  bio: string;
  teamId: string | null;
  teamColor: string;
  approval: "approved" | "pending";
};
export type Team = {
  logoIcon: string;
  id: string;
  name: string;
  color: string;
  captainUserId: string | null;
  captainName: string;
  playerCount: number;
};
export type Organizer = {
  id: string;
  name: string;
  avatarId: string | null;
  isOwner: boolean;
};
export type Message = {
  id: string;
  body: string;
  authorId: string;
  authorName: string;
  avatarId: string | null;
  createdAt: string;
};
export type ScheduleItem = {
  id: string;
  time: string;
  title: string;
  description: string;
};
export type GearItem = {
  id: string;
  name: string;
  quantity: number;
  cost: number;
  category: "bring" | "rental" | "shared";
};
export type Announcement = { id: string; body: string; createdAt: string };
export type Poll = {
  id: string;
  question: string;
  options: Array<{ id: string; label: string; votes: number }>;
  myVote?: string;
};
export type Sponsor = { id: string; name: string; url: string };
export type EventDetail = {
  teamPlayers: Guest[];
  sponsors: Sponsor[];
  event: Event;
  guests: Guest[];
  schedule: ScheduleItem[];
  gear: GearItem[];
  announcements: Announcement[];
  polls: Poll[];
  isOwner: boolean;
  currentGuest: Guest | null;
  guestEditToken: string | null;
  viewer: User | null;
  isOrganizer: boolean;
  isMember: boolean;
  canViewRoster: boolean;
  canMessage: boolean;
  teams: Team[];
  organizers: Organizer[];
  messages: Message[];
  guestTotal: number;
  messageTotal: number;
  guestPage: number;
  messagePage: number;
  goingCount: number;
  estimatedCost: number;
  pendingGuests: Guest[];
  memberCandidates: Array<{ id: string; name: string }>;
};
export type SiteSettings = {
  landingTitle: string;
  landingSubtitle: string;
  landingCta: string;
  accentColor: string;
  discoveryEnabled: boolean;
  publicProfilesEnabled: boolean;
  sponsorsEnabled: boolean;
  registrationEnabled: boolean;
  eventCreationEnabled: boolean;
  siteNotice: string;
};
export type AdminOverview = {
  users: number;
  events: number;
  guests: number;
  upcomingEvents: number;
  recentActivity: Array<{
    id: string;
    action: string;
    detail: string;
    createdAt: string;
  }>;
  recentUsers: Array<{
    id: string;
    name: string;
    email: string;
    createdAt: string;
    eventCount: number;
  }>;
  recentEvents: Array<{
    id: string;
    title: string;
    ownerName: string;
    date: string;
    guestCount: number;
  }>;
  settings: SiteSettings;
};
